version: '3'

volumes:
  dbdata:

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=sOme-bulLshit_dEv-seCret
      - "DATABASE_URL=sqlite:////db/microblog.db"
    command: flask run --host=0.0.0.0
    volumes:
      - ./microblog:/code
      - dbdata:/db
